<?php

/**
 * Created by PhpStorm.
 * User: prabhato
 * Date: 5/18/2017
 * Time: 8:57 PM
 */
class AppInfoTable
{
    public static $TABLE_NAME = "app_info";

    public static $APP_ID = "APP_ID";
    public static $NAME = "NAME";
    public static $IS_ON = "IS_ON";
    public static $LINK = "LINK";
    public static $SAME_GENDER = "SAME_GENDER";
    public static $FOLLOWER_FILTER = "FOLLOWER_FILTER";
    public static $FRIENDS_FILTER = "FRIENDS_FILTER";
}